<a href="https://colab.research.google.com/github/NGoyal22/Machine_Leaning_using_python/blob/master/Neeraj_LR.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Instead of using iris I used real-estate price prediction data here, as it is more relevant to your task
!ls

sample_data


In [2]:
# importing required libraries
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn import metrics
from sklearn.linear_model import LinearRegression

In [4]:
df = pd.read_csv('./Real-estate.csv')
df.head()

No  X1 transaction date  X2 house age  \
0   1             2012.917          32.0   
1   2             2012.917          19.5   
2   3             2013.583          13.3   
3   4             2013.500          13.3   
4   5             2012.833           5.0   

   X3 distance to the nearest MRT station  X4 number of convenience stores  \
0                                84.87882                               10   
1                               306.59470                                9   
2                               561.98450                                5   
3                               561.98450                                5   
4                               390.56840                                5   

   X5 latitude  X6 longitude  Y house price of unit area  
0     24.98298     121.54024                        37.9  
1     24.98034     121.53951                        42.2  
2     24.98746     121.54391                        47.3  
3     24.98746     121.54391                        54.8  
4     24.97937     121.54245                        43.1

In [5]:
df.shape # we have 8 columns and 414 datapoints/rows

(414, 8)

In [6]:
df.columns # we have 6 features

Index(['No', 'X1 transaction date', 'X2 house age',
       'X3 distance to the nearest MRT station',
       'X4 number of convenience stores', 'X5 latitude', 'X6 longitude',
       'Y house price of unit area'],
      dtype='object')

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 414 entries, 0 to 413
Data columns (total 8 columns):
 #   Column                                  Non-Null Count  Dtype  
---  ------                                  --------------  -----  
 0   No                                      414 non-null    int64  
 1   X1 transaction date                     414 non-null    float64
 2   X2 house age                            414 non-null    float64
 3   X3 distance to the nearest MRT station  414 non-null    float64
 4   X4 number of convenience stores         414 non-null    int64  
 5   X5 latitude                             414 non-null    float64
 6   X6 longitude                            414 non-null    float64
 7   Y house price of unit area              414 non-null    float64
dtypes: float64(6), int64(2)
memory usage: 26.0 KB


In [8]:
# You can further look into data by plotting various graphs but here i'm diving the columns to start training the model
X=df[['X1 transaction date','X2 house age','X3 distance to the nearest MRT station','X4 number of convenience stores','X5 latitude','X6 longitude']]
X

X1 transaction date  X2 house age  \
0               2012.917          32.0   
1               2012.917          19.5   
2               2013.583          13.3   
3               2013.500          13.3   
4               2012.833           5.0   
..                   ...           ...   
409             2013.000          13.7   
410             2012.667           5.6   
411             2013.250          18.8   
412             2013.000           8.1   
413             2013.500           6.5   

     X3 distance to the nearest MRT station  X4 number of convenience stores  \
0                                  84.87882                               10   
1                                 306.59470                                9   
2                                 561.98450                                5   
3                                 561.98450                                5   
4                                 390.56840                                5   
..                                      ...                              ...   
409                              4082.01500                                0   
410                                90.45606                                9   
411                               390.96960                                7   
412                               104.81010                                5   
413                                90.45606                                9   

     X5 latitude  X6 longitude  
0       24.98298     121.54024  
1       24.98034     121.53951  
2       24.98746     121.54391  
3       24.98746     121.54391  
4       24.97937     121.54245  
..           ...           ...  
409     24.94155     121.50381  
410     24.97433     121.54310  
411     24.97923     121.53986  
412     24.96674     121.54067  
413     24.97433     121.54310  

[414 rows x 6 columns]

In [9]:
y=df['Y house price of unit area']
y

0      37.9
1      42.2
2      47.3
3      54.8
4      43.1
       ... 
409    15.4
410    50.0
411    40.6
412    52.5
413    63.9
Name: Y house price of unit area, Length: 414, dtype: float64

In [10]:
# Splitting data for training and testing
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3,random_state=101)

In [11]:
print(X_train.shape)
print(y_train.shape)

(289, 6)
(289,)


In [12]:
print(X_test.shape)
print(y_test.shape)

(125, 6)
(125,)


In [13]:
# initializing the model
model = LinearRegression()
# fitting the model
model.fit(X_train,y_train)

LinearRegression()

In [14]:
# Testing the model
y_pred = model.predict(X_test)
y_pred

array([12.63830383, 10.0304461 , 22.98807375, 48.50264837, 32.67140451,
       37.82572669, 36.09178068, 41.05953639, 47.84830793, 40.4574746 ,
       45.0361603 , 32.86533457, 40.48623576, 36.48827849, 44.30595729,
       46.59668235, 38.42798244, 44.26307337, 48.81959723, 45.50409246,
       42.23260833, 54.6526397 , 48.07373298, 37.48194231, 33.57091525,
       48.26293154, 40.23479801, 50.42675437, 47.22333423, 38.99458517,
       48.11033139, 40.47035604, 45.61060308, 43.98441528, 46.54336092,
        8.18725886, 38.08375879, 39.82608171,  8.5339677 , 55.72740213,
       32.17950939, 49.72698264, 24.85604948, 47.64473233, 41.23026871,
       51.17703175, 42.04716292, 37.32689765, 44.24427856, 36.27028988,
       47.55408451, 34.74054504, 43.53329366, 15.95586215, 38.29001222,
       48.93912385, 44.69790471, 44.91934627, 45.33972278, 41.33035787,
       34.39899173, 44.02303164, 41.99940522, 43.9553153 , 53.61420366,
       44.24994361, 24.68926603, 47.06140631, 31.22031534, 40.49

In [15]:
print('Mean Absolute error:',metrics.mean_absolute_error(y_test, y_pred))
print('Mean Squared Error:',metrics.mean_squared_error(y_test, y_pred))
print('Root Mean Squared Error',np.sqrt(metrics.mean_squared_error(y_test, y_pred)))

# read more about metrics from here https://scikit-learn.org/stable/modules/classes.html#regression-metrics

Mean Absolute error: 5.392293684756716
Mean Squared Error: 46.2117978349358
Root Mean Squared Error 6.797925995105846


In [16]:
#Done (but this is a raddi model as we trained on all the given features)

In [17]:
print(model.predict(X_test.head(5)))
print(y_test.head(5))

[12.63830383 10.0304461  22.98807375 48.50264837 32.67140451]
176    19.2
347    11.2
307    24.7
299    46.1
391    31.3
Name: Y house price of unit area, dtype: float64


SVM Training

In [18]:
from sklearn.svm import SVR

In [19]:
svm_model = SVR(kernel='linear')

In [20]:
svm_model.fit(X_train,y_train)

SVR(kernel='linear')

In [21]:
svm_y_pred= svm_model.predict(X_test)

In [22]:
print('Mean Absolute error:',metrics.mean_absolute_error(y_test,svm_y_pred))
print('Mean Squared Error:',metrics.mean_squared_error(y_test, svm_y_pred))
print('Root Mean Squared Error',np.sqrt(metrics.mean_squared_error(y_test,svm_y_pred)))

Mean Absolute error: 5.419461455725137
Mean Squared Error: 50.60005727343251
Root Mean Squared Error 7.113371723271076


In [23]:
print(model.predict(X_test.head(5)))
print(y_test.head(5))
# same prediction as LR 

[12.63830383 10.0304461  22.98807375 48.50264837 32.67140451]
176    19.2
347    11.2
307    24.7
299    46.1
391    31.3
Name: Y house price of unit area, dtype: float64


In [24]:
# inoy neraachhh